INSERT INTO PERSON VALUES('20', 'amale', 'M');
INSERT INTO PERSON VALUES('21', 'afemale', 'F');
INSERT INTO PERSON VALUES('22', 'man', 'M');
INSERT INTO PERSON VALUES('23', 'woman', 'F');
INSERT INTO PERSON VALUES('24', 'auto', 'M');
INSERT INTO PERSON VALUES('25', 'auta', 'F');
